### ISSUE TITLE
Change User name?

### ISSUE THREAD

**Issue by robertmuehsig** [pydt/web#11]
Hi
I noticed that I (somehow) created my steam profile with my full name, which is cool because everyone can google me and this is also quite bad ;) 

In my steam account I also added a NickName, unfortunatly after signing up I can't change my name.

So the question is: Would it be possible to change the name via the Website?

**Comment by mrosack** [comment]
Are you sure there's no way to update it through steam?  My steam username is mrosack, but my community persona name that gets displayed on the site is SackGT.

**Comment by mrosack** [comment]
Once every couple hours a process runs on PYDT to sync account information with steam, so if you're not seeing changes on PYDT that could be why.

**Comment by robertmuehsig** [comment]
Ah - changed it on my Steam Profile... will reopen it if I have any issues with that ;)

Thank! Great tool btw!

**Comment by robertmuehsig** [comment]
(just a follow up: it works 👍  thanks! )
